version: "3"

volumes:
  dbgate-data:
    driver: local

services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 80:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1
      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: TEST
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
